# Generated by Django 4.2.5 on 2024-04-06 20:52

import App.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateTimeField(validators=[App.models.validate_date])),
                ('type', models.CharField(choices=[('Compañia', 'Compañia'), ('Independiente', 'Independiente')], max_length=100, null=True)),
                ('image_profile', models.ImageField(blank=True, default='profile_default.png', upload_to='profile')),
                ('note', models.TextField(blank=True)),
                ('directions', models.CharField(max_length=150)),
                ('id_tribute', models.PositiveBigIntegerField()),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'editores',
            },
        ),
        migrations.CreateModel(
            name='Rango_Prefijo_Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_inferior', models.PositiveIntegerField()),
                ('rango_superior', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('P-Menor', 'P-Menor'), ('P-Medio', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rangos-Editores',
            },
        ),
        migrations.CreateModel(
            name='Rango_Prefijo_Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_superior', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('P-Menor', 'P-Menor'), ('P-Media', 'P-Medio'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Superior', 'P-Superior'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rango-Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Registered_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporal', models.JSONField()),
                ('tipo', models.CharField(choices=[('Solicitud-Inscripción', 'Solicitud-Inscripción'), ('Solicitud-ISMN', 'Solicitud-ISMN')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], max_length=50)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.editor')),
            ],
            options={
                'verbose_name_plural': 'solicitudes',
            },
        ),
        migrations.CreateModel(
            name='PrefijoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('lote', models.CharField(max_length=7)),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.rango_prefijo_publicacion')),
            ],
            options={
                'verbose_name_plural': 'Publicaciones Prefijos',
            },
        ),
        migrations.CreateModel(
            name='PrefijoEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True)),
                ('lote', models.CharField(max_length=7)),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.rango_prefijo_editor')),
            ],
            options={
                'verbose_name_plural': 'Prefijos-Editores',
            },
        ),
        migrations.CreateModel(
            name='Musical_Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('ismn', models.CharField(max_length=20, unique=True)),
                ('barcode', models.ImageField(upload_to='publications/barcodes')),
                ('letra', models.FileField(upload_to='publications/letters')),
                ('description', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, default='default.jpg', upload_to='publications')),
                ('date_time', models.DateTimeField(validators=[App.models.validate_date])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Bolero', 'BL'), ('Popular Bailable', 'PB'), ('Mambo', 'MB'), ('Chachacha', 'CH'), ('Rumba', 'RB'), ('Danzón', 'DZ')], max_length=100, null=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.editor')),
                ('prefijo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.prefijopublicacion')),
            ],
            options={
                'verbose_name_plural': 'publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('image_profile', models.ImageField(blank=True, default='profile_default.png', upload_to='profile')),
                ('directions', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'especialistas',
            },
        ),
        migrations.AddField(
            model_name='editor',
            name='prefijo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='App.prefijoeditor'),
        ),
        migrations.AddField(
            model_name='editor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
