# Generated by Django 4.2.2 on 2023-07-12 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musical_Publication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ismn', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(20)])),
                ('letter_contain', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('imagen', models.ImageField(default='default.jpg', null=True, upload_to='publications')),
                ('date_time', models.DateField()),
                ('gender', models.CharField(choices=[('BL', 'Bolero'), ('PB', 'Popular Bailable'), ('MB', 'Mambo'), ('CHA', 'Chachacha'), ('RMB', 'Rumba'), ('DZ', 'Danzón')], max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(120), django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=2),
        ),
    ]
