# Generated by Django 4.2.5 on 2024-02-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('I', 'Independiente'), ('C', 'Compañia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prefijo',
            name='tipo',
            field=models.CharField(choices=[('PM', 'Publicacion Musical'), ('E', 'Editor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rango_prefijo',
            name='tipo',
            field=models.CharField(choices=[('Superior', 'Superior'), ('Medio Inferior', 'Medio Inferior'), ('Inferior', 'Inferior'), ('Medio', 'Medio')], max_length=20, unique=True),
        ),
    ]
