# Generated by Django 5.0.4 on 2024-06-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_data',
            name='CI',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Superior', 'P-Superior'), ('P-Medio', 'P-Medio'), ('P-Menor', 'P-Menor')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior'), ('P-Menor', 'P-Menor'), ('P-Media_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registered_data',
            name='id_tribute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Solicitud-Inscripción', 'Solicitud-Inscripción'), ('Solicitud-ISMN', 'Solicitud-ISMN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('RU', 'Ruso'), ('EN', 'Inglés'), ('ES', 'Español')], max_length=50),
        ),
    ]
