# Generated by Django 4.2.5 on 2024-04-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_registered_data_id_tribute_alter_editor_id_tribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musical_publication',
            name='gender',
            field=models.CharField(choices=[('Bolero', 'BL'), ('Fusion', 'FS'), ('Popular Bailable', 'PB'), ('Mambo', 'MB'), ('Chachacha', 'CH'), ('Rumba', 'RB'), ('Danzón', 'DZ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior'), ('P-Menor', 'P-Menor'), ('P-Medio', 'P-Medio')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Media', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Menor', 'P-Menor'), ('P-Media_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], max_length=50),
        ),
    ]
