# Generated by Django 4.2.5 on 2024-02-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_editor_type_alter_prefijo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='musical_publication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prefijo',
            name='tipo',
            field=models.CharField(choices=[('E', 'Editor'), ('PM', 'Publicacion Musical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rango_prefijo',
            name='tipo',
            field=models.CharField(choices=[('Inferior', 'Inferior'), ('Superior', 'Superior'), ('Medio Inferior', 'Medio Inferior'), ('Medio', 'Medio')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('ISMNADDS', 'Solicitud-ISMN'), ('EADDS', 'Solicitud-Inscripción')], max_length=50),
        ),
    ]
