# Generated by Django 4.2.5 on 2024-04-07 03:22

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_musical_publication_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, validators=[App.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Compañia', 'Compañia'), ('Independiente', 'Independiente')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior'), ('P-Menor', 'P-Menor'), ('P-Medio_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Superior', 'P-Superior'), ('P-Menor', 'P-Menor'), ('P-Media', 'P-Medio')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Atendido', 'Atendido'), ('Pendiente', 'Pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Solicitud-Inscripción', 'Solicitud-Inscripción'), ('Solicitud-ISMN', 'Solicitud-ISMN')], max_length=50),
        ),
    ]
