# Generated by Django 4.2.5 on 2024-02-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_editor_id_alter_musical_publication_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango_prefijo',
            name='tipo',
            field=models.CharField(choices=[('Superior', 'Superior'), ('Medio Inferior', 'Medio Inferior'), ('Inferior', 'Inferior'), ('Medio', 'Medio')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('ATEND', 'Atendido'), ('PEND', 'Pendiente')], max_length=50),
        ),
        migrations.CreateModel(
            name='PrefijoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(unique=True)),
                ('lote', models.CharField(max_length=7)),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.rango_prefijo')),
            ],
            options={
                'verbose_name_plural': 'prefijos',
            },
        ),
        migrations.CreateModel(
            name='PrefijoEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(unique=True)),
                ('lote', models.CharField(max_length=7)),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.rango_prefijo')),
            ],
            options={
                'verbose_name_plural': 'prefijos',
            },
        ),
        migrations.AlterField(
            model_name='editor',
            name='prefijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.prefijoeditor'),
        ),
        migrations.AlterField(
            model_name='musical_publication',
            name='prefijo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='App.prefijopublicacion'),
        ),
        migrations.DeleteModel(
            name='Prefijo',
        ),
    ]
