# Generated by Django 5.0.4 on 2024-05-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_editor_type_alter_rango_prefijo_editor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Independiente', 'Independiente'), ('Compañia', 'Compañia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Menor', 'P-Menor'), ('P-Medio', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Menor', 'P-Menor'), ('P-Superior', 'P-Superior'), ('P-Media', 'P-Medio'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Atendido', 'Atendido'), ('Pendiente', 'Pendiente')], max_length=50),
        ),
    ]
