# Generated by Django 4.2.5 on 2024-03-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_registered_data_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Compañia', 'Compañia'), ('Independiente', 'Independiente')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musical_publication',
            name='letra',
            field=models.FileField(upload_to='publications'),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Menor', 'P-Menor'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Medio', 'P-Medio'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Menor', 'P-Menor'), ('P-Media', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Media_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], max_length=50),
        ),
    ]
