# Generated by Django 4.2.2 on 2023-08-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_editor_delete_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='gender',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=100, null=True),
        ),
    ]
