# Generated by Django 4.2.2 on 2023-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_editor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
