# Generated by Django 5.0.4 on 2024-05-10 16:35

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_editor_type_alter_rango_prefijo_editor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='id_tribute',
            field=models.PositiveBigIntegerField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='editor',
            name='image_profile',
            field=models.ImageField(blank=True, default='profile_default.png', upload_to='profile', validators=[App.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Independiente', 'Independiente'), ('Compañia', 'Compañia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Menor', 'P-Menor'), ('P-Superior', 'P-Superior'), ('P-Medio_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Menor', 'P-Menor'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
    ]
