# Generated by Django 5.0.4 on 2024-06-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_descripciondigital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musical_publication',
            name='descripcion_general',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Medio', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Medio_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Media', 'P-Medio')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Solicitud-ISMN', 'Solicitud-ISMN'), ('Solicitud-Inscripción', 'Solicitud-Inscripción')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('EN', 'Inglés'), ('ES', 'Español'), ('RU', 'Ruso')], max_length=50),
        ),
    ]
