# Generated by Django 4.2.2 on 2023-08-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_editor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='editor',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='editor',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='musical_publication',
            name='ismn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
