# Generated by Django 5.0.4 on 2024-05-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_editor_id_tribute_alter_editor_image_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='id_tribute',
            field=models.PositiveSmallIntegerField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio', 'P-Medio'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior'), ('P-Menor', 'P-Menor')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior'), ('P-Media', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Menor', 'P-Menor')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Atendido', 'Atendido'), ('Pendiente', 'Pendiente')], max_length=50),
        ),
    ]
