# Generated by Django 4.2.5 on 2024-02-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_prefijoeditor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Compañia', 'Compañia'), ('Independiente', 'Independiente')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Menor', 'P-Menor'), ('P-Inferior', 'P-Inferior'), ('P-Medio', 'P-Medio'), ('P-Medio_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('ATEND', 'Atendido'), ('PEND', 'Pendiente')], max_length=50),
        ),
    ]
