# Generated by Django 4.2.5 on 2024-02-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_editor_type_alter_rango_prefijo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefijoeditor',
            options={'verbose_name_plural': 'Prefijos_Editores'},
        ),
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Independiente', 'Independiente'), ('Compañia', 'Compañia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prefijopublicacion',
            name='value',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rango_prefijo',
            name='tipo',
            field=models.CharField(choices=[('P-Menor', 'P-Menor'), ('P-Inferior', 'P-Inferior'), ('P-Medio', 'P-Medio'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('ISMNADDS', 'Solicitud-ISMN'), ('EADDS', 'Solicitud-Inscripción')], max_length=50),
        ),
    ]
