# Generated by Django 5.0.4 on 2024-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_editor_id_tribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='id_tribute',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Menor', 'P-Menor'), ('P-Medio', 'P-Medio'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Superior', 'P-Superior'), ('P-Media', 'P-Medio'), ('P-Menor', 'P-Menor'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], max_length=50),
        ),
    ]
