# Generated by Django 5.0.4 on 2024-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_musical_publication_descripcion_general_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musical_publication',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='musical_publication',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(choices=[('CUB', 'Cuba'), ('ITA', 'Italia'), ('EUA', 'Estados Unidos'), ('RU', 'Rusia'), ('MX', 'Mexico'), ('FR', 'Francia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Medio', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('FR', 'Francés'), ('EN', 'Inglés'), ('ES', 'Español'), ('RU', 'Ruso'), ('PO', 'Portugués'), ('IT', 'Italiano'), ('AL', 'Alemán')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='tipo_publicacion',
            field=models.CharField(choices=[('P', 'Partitura'), ('PO', 'Partitura de Orquesta'), ('RP', 'Reducción para Piano'), ('PV', 'Partitura Vocal'), ('CPI', 'Conjunto de partes instrumentales')], max_length=50),
        ),
    ]
