# Generated by Django 4.2.2 on 2023-08-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_registered_email_alter_editor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Registered_email',
        ),
        migrations.AlterField(
            model_name='editor',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=100, null=True),
        ),
    ]
