# Generated by Django 4.2.5 on 2024-02-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_prefijoeditor_options_alter_editor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Compañia', 'Compañia'), ('Independiente', 'Independiente')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Medio', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Menor', 'P-Menor')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('ATEND', 'Atendido')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('EADDS', 'Solicitud-Inscripción'), ('ISMNADDS', 'Solicitud-ISMN')], max_length=50),
        ),
    ]
