# Generated by Django 4.2.5 on 2024-02-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_editor_type_alter_rango_prefijo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Independiente', 'Independiente'), ('Compañia', 'Compañia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musical_publication',
            name='imagen',
            field=models.ImageField(auto_created=True, default='default.jpg', upload_to='publications'),
        ),
        migrations.AlterField(
            model_name='rango_prefijo',
            name='tipo',
            field=models.CharField(choices=[('P-Menor', 'P-Menor'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Medio', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('ISMNADDS', 'Solicitud-ISMN'), ('EADDS', 'Solicitud-Inscripción')], max_length=50),
        ),
    ]
