# Generated by Django 5.0.4 on 2024-06-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_rename_autor_musical_publication_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musical_publication',
            name='autores_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Medio', 'P-Medio'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Inferior', 'P-Inferior'), ('P-Media', 'P-Medio'), ('P-Media_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('FR', 'Francés'), ('EN', 'Inglés'), ('RU', 'Ruso'), ('PO', 'Portugués'), ('AL', 'Alemán'), ('IT', 'Italiano'), ('ES', 'Español')], max_length=50),
        ),
    ]
