# Generated by Django 4.2.2 on 2023-08-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_editor_gender_alter_registered_data_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Registered_Data',
        ),
        migrations.AlterField(
            model_name='editor',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=100, null=True),
        ),
    ]
