# Generated by Django 4.2.2 on 2023-08-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_registered_email_delete_registered_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Registered_email',
        ),
        migrations.AlterField(
            model_name='editor',
            name='gender',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=100, null=True),
        ),
    ]
