# Generated by Django 5.0.4 on 2024-05-26 19:20

import App.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_rango_prefijo_editor_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Independiente', 'Independiente'), ('Compañia', 'Compañia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Medio', 'P-Medio'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Menor', 'P-Menor'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Media', 'P-Medio'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Menor', 'P-Menor'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='HistoricalEditor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=14, validators=[App.models.validate_phone])),
                ('birthday', models.DateField(blank=True, null=True, validators=[App.models.validate_date])),
                ('type', models.CharField(choices=[('Independiente', 'Independiente'), ('Compañia', 'Compañia')], max_length=100)),
                ('image_profile', models.TextField(blank=True, default='profile_default.png', max_length=100, validators=[App.models.validate_image_extension])),
                ('note', models.TextField(blank=True)),
                ('directions', models.CharField(max_length=150)),
                ('id_tribute', models.PositiveSmallIntegerField(db_index=True)),
                ('state', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prefijo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='App.prefijoeditor')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical editor',
                'verbose_name_plural': 'historical editores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalEspecialista',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=14, validators=[App.models.validate_phone])),
                ('note', models.TextField(blank=True)),
                ('image_profile', models.TextField(blank=True, default='profile_default.png', max_length=100, validators=[App.models.validate_image_extension])),
                ('directions', models.CharField(max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical especialista',
                'verbose_name_plural': 'historical especialistas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalMusical_Publication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('ismn', models.CharField(db_index=True, max_length=20)),
                ('barcode', models.TextField(max_length=100)),
                ('letra', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('imagen', models.TextField(blank=True, default='default.jpg', max_length=100)),
                ('date_time', models.DateTimeField(validators=[App.models.validate_date])),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('gender', models.CharField(choices=[('Bolero', 'BL'), ('Fusion', 'FS'), ('Popular Bailable', 'PB'), ('Mambo', 'MB'), ('Chachacha', 'CH'), ('Rumba', 'RB'), ('Danzón', 'DZ')], max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('editor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='App.editor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prefijo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='App.prefijopublicacion')),
            ],
            options={
                'verbose_name': 'historical musical_ publication',
                'verbose_name_plural': 'historical publicaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalSolicitud',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('temporal', models.JSONField()),
                ('tipo', models.CharField(choices=[('Solicitud-Inscripción', 'Solicitud-Inscripción'), ('Solicitud-ISMN', 'Solicitud-ISMN')], max_length=50)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('Atendido', 'Atendido'), ('Pendiente', 'Pendiente')], max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('editor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='App.editor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical solicitud',
                'verbose_name_plural': 'historical solicitudes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
        ),
    ]
