# Generated by Django 5.0.4 on 2024-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_musical_publication_autores_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Medio', 'P-Medio'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior'), ('P-Media', 'P-Medio'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Solicitud-ISMN', 'Solicitud-ISMN'), ('Solicitud-Inscripción', 'Solicitud-Inscripción')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('RU', 'Ruso'), ('FR', 'Francés'), ('AL', 'Alemán'), ('IT', 'Italiano'), ('PO', 'Portugués'), ('EN', 'Inglés'), ('ES', 'Español')], max_length=50),
        ),
    ]
