# Generated by Django 4.2.5 on 2024-02-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_rango_prefijo_editor_rango_prefijo_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Medio', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Inferior', 'P-Inferior'), ('P-Menor', 'P-Menor')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Inferior', 'P-Inferior'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Menor', 'P-Menor'), ('P-Media', 'P-Medio')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('EADDS', 'Solicitud-Inscripción'), ('ISMNADDS', 'Solicitud-ISMN')], max_length=50),
        ),
    ]
