# Generated by Django 4.2.5 on 2024-03-02 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_rango_prefijo_editor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefijoeditor',
            options={'verbose_name_plural': 'Prefijos-Editores'},
        ),
        migrations.AlterModelOptions(
            name='rango_prefijo_editor',
            options={'verbose_name_plural': 'Rangos-Editores'},
        ),
        migrations.AlterModelOptions(
            name='rango_prefijo_publicacion',
            options={'verbose_name_plural': 'Rango-Publicaciones'},
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='asunto',
        ),
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Independiente', 'Independiente'), ('Compañia', 'Compañia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musical_publication',
            name='prefijo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.prefijopublicacion'),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior'), ('P-Medio', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Menor', 'P-Menor')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior'), ('P-Media', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Menor', 'P-Menor')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.editor'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Atendido')], max_length=50),
        ),
    ]
