# Generated by Django 5.0.4 on 2024-08-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_rango_prefijo_editor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior'), ('P-Medio', 'P-Medio'), ('P-Medio_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Media', 'P-Medio')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registered_data',
            name='CI',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Solicitud-ISMN', 'Solicitud-ISMN'), ('Solicitud-Inscripción', 'Solicitud-Inscripción')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('AL', 'Alemán'), ('PO', 'Portugués'), ('ES', 'Español'), ('RU', 'Ruso'), ('EN', 'Inglés'), ('IT', 'Italiano'), ('FR', 'Francés')], max_length=50),
        ),
    ]
