# Generated by Django 4.2.5 on 2024-03-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_prefijoeditor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefijoeditor',
            name='value',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='prefijopublicacion',
            name='value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='rango_inferior',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='rango_superior',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Menor', 'P-Menor'), ('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior'), ('P-Medio', 'P-Medio'), ('P-Medio_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='rango_superior',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media', 'P-Medio'), ('P-Menor', 'P-Menor'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('A', 'Atendido'), ('P', 'Pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('ISMNADDS', 'Solicitud-ISMN'), ('EADDS', 'Solicitud-Inscripción')], max_length=50),
        ),
    ]
