# Generated by Django 4.2.5 on 2024-03-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_prefijoeditor_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='type',
            field=models.CharField(choices=[('Compañia', 'Compañia'), ('Independiente', 'Independiente')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Menor', 'P-Menor'), ('P-Inferior', 'P-Inferior'), ('P-Medio', 'P-Medio'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Menor', 'P-Menor'), ('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior'), ('P-Media', 'P-Medio'), ('P-Media_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
    ]
