# Generated by Django 5.0.4 on 2024-08-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_rango_prefijo_editor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='CI',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='editor',
            name='id_tribute',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='id_tribute',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='CI',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Medio', 'P-Medio'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Media', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Media_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registered_data',
            name='id_tribute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('EN', 'Inglés'), ('IT', 'Italiano'), ('PO', 'Portugués'), ('RU', 'Ruso'), ('FR', 'Francés'), ('ES', 'Español'), ('AL', 'Alemán')], max_length=50),
        ),
    ]
