# Generated by Django 5.0.4 on 2024-08-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_rango_prefijo_editor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Medio', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Medio_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Superior', 'P-Superior'), ('P-Media', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Media_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Solicitud-Inscripcion', 'Solicitud-Inscripcion'), ('Solicitud-ISMN', 'Solicitud-ISMN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('FR', 'Francés'), ('ES', 'Español'), ('RU', 'Ruso'), ('AL', 'Alemán'), ('PO', 'Portugués'), ('EN', 'Inglés'), ('IT', 'Italiano')], max_length=50),
        ),
    ]
