# Generated by Django 5.0.4 on 2024-08-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_rango_prefijo_editor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio', 'P-Medio'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Superior', 'P-Superior'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Media', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Atendido', 'Atendido'), ('Pendiente', 'Pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Solicitud-ISMN', 'Solicitud-ISMN'), ('Solicitud-Inscripcion', 'Solicitud-Inscripcion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('IT', 'Italiano'), ('RU', 'Ruso'), ('PO', 'Portugués'), ('FR', 'Francés'), ('ES', 'Español'), ('EN', 'Inglés'), ('AL', 'Alemán')], max_length=50),
        ),
    ]
