# Generated by Django 5.0.4 on 2024-08-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_rango_prefijo_editor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media', 'P-Medio'), ('P-Superior', 'P-Superior'), ('P-Inferior', 'P-Inferior'), ('P-Media_Inferior', 'P-Medio_Inferior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Solicitud-ISMN', 'Solicitud-ISMN'), ('Solicitud-Inscripcion', 'Solicitud-Inscripcion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('FR', 'Francés'), ('PO', 'Portugués'), ('EN', 'Inglés'), ('AL', 'Alemán'), ('RU', 'Ruso'), ('IT', 'Italiano'), ('ES', 'Español')], max_length=50),
        ),
    ]
