# Generated by Django 5.0.4 on 2024-08-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_rango_prefijo_editor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior'), ('P-Medio', 'P-Medio'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Media', 'P-Medio'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('RU', 'Ruso'), ('EN', 'Inglés'), ('AL', 'Alemán'), ('PO', 'Portugués'), ('IT', 'Italiano'), ('ES', 'Español'), ('FR', 'Francés')], max_length=50),
        ),
    ]
