# Generated by Django 4.2 on 2024-08-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_alter_rango_prefijo_editor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango_prefijo_editor',
            name='tipo',
            field=models.CharField(choices=[('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Medio', 'P-Medio'), ('P-Inferior', 'P-Inferior'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_prefijo_publicacion',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Media_Inferior', 'P-Medio_Inferior'), ('P-Media', 'P-Medio'), ('P-Superior', 'P-Superior')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='idioma',
            field=models.CharField(choices=[('AL', 'Alemán'), ('IT', 'Italiano'), ('ES', 'Español'), ('EN', 'Inglés'), ('PO', 'Portugués'), ('RU', 'Ruso'), ('FR', 'Francés')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.municipio'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.provincia'),
        ),
    ]
